__author__ = 'ynh'

__all__ = ['SHORTCUTS']

SHORTCUTS = {u':)': u':smile:',
             u':-)': u':smile:',
             u':D': u':smiley:',
             u';D': u':joy:',
             u';-D': u':joy:',
             u':-D': u':smiley:',
             u':d': u':smiley:',
             u'x-D': u':satisfied:',
             u'xd': u':satisfied:',
             u'xD': u':satisfied:',
             u'x-d': u':satisfied:',
             u':-O': u':open_mouth:',
             u':o': u':open_mouth:',
             u'>:o': u':angry:',
             u':p': u':stuck_out_tongue:',
             u':-P': u':stuck_out_tongue:',
             u'xp': u':stuck_out_tongue_closed_eyes:',
             u'x-P': u':stuck_out_tongue_closed_eyes:',
             u';-P': u':stuck_out_tongue_winking_eye:',
             u';P': u':stuck_out_tongue_winking_eye:',
             u';-)': u':wink:',
             u';)': u':wink:',
             u'B-)': u':sunglasses:',
             u'8-)': u':sunglasses:',
             u'8)': u':sunglasses:',
             u'O:)': u':innocent:',
             u'o:)': u':innocent:',
             u':*': u':kissing_heart:',
             u':-*': u':kissing_heart:',
             u':/': u':confused:',
             u':\\': u':confused:',
             u':-(': u':worried:',
             u'<3':u':heart:',
             u':(': u':worried:',
             u':S': u':confounded:',
             u':s': u':confounded:',
             u':-|': u':expressionless:',
             u':|': u':expressionless:',
             u':`(': u':cry:',
             u';(': u':cry:',
             u':\'(': u':cry:',
             u':-$': u':flushed:',
             u':$': u':flushed:',
             u'(y)': u':+1:',
             u'(n)': u':-1:',
             u':omg:': u':scream:'
             }
